VPN config fixes
1194 udp disabled, port-share added, logging (except critical) disabled

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -21,7 +21,7 @@ chmod 600 key.pem
 
 [ -f tcp443.conf ] || cat >tcp443.conf <<EOF
 server 192.168.255.0 255.255.255.128
-verb 3
+verb 0
 duplicate-cn
 key key.pem
 ca cert.pem
@@ -35,35 +35,19 @@ push "dhcp-option DNS 8.8.4.4"
 
 proto tcp-server
 port 443
+port-share 127.0.0.1 4443
 dev tun443
 status openvpn-status-443.log
 EOF
 
-[ -f udp1194.conf ] || cat >udp1194.conf <<EOF
-server 192.168.255.128 255.255.255.128
-verb 3
-duplicate-cn
-key key.pem
-ca cert.pem
-cert cert.pem
-dh dh.pem
-keepalive 10 60
-persist-key
-persist-tun
-push "dhcp-option DNS 8.8.8.8"
-push "dhcp-option DNS 8.8.4.4"
-
-proto udp
-port 1194
-dev tun1194
-status openvpn-status-1194.log
-EOF
-
 MY_IP_ADDR=$(curl -s http://myip.enix.org/REMOTE_ADDR)
 [ "$MY_IP_ADDR" ] || {
-    echo "Sorry, I could not figure out my public IP address."
-    echo "(I use http://myip.enix.org/REMOTE_ADDR/ for that purpose.)"
-    exit 1
+    MY_IP_ADDR=$(curl -s ifconfig.co)
+    [ "$MY_IP_ADDR" ] || {
+        echo "Sorry, I could not figure out my public IP address."
+        echo "(I use http://myip.enix.org/REMOTE_ADDR/ and ifconfig.co for that purpose.)"
+        exit 1
+    }
 }
 
 [ -f client.ovpn ] || cat >client.ovpn <<EOF
@@ -86,10 +70,6 @@ redirect-gateway def1
 </dh>
 
 <connection>
-remote $MY_IP_ADDR 1194 udp
-</connection>
-
-<connection>
 remote $MY_IP_ADDR 443 tcp-client
 </connection>
 EOF
@@ -106,5 +86,4 @@ iptables -t nat -A POSTROUTING -s 192.168.255.0/24 -o eth0 -j MASQUERADE
 
 touch tcp443.log udp1194.log http8080.log
 while true ; do openvpn tcp443.conf ; done >> tcp443.log &
-while true ; do openvpn udp1194.conf ; done >> udp1194.log &
 tail -F *.log
